[package]
name = "hyperspeed"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ftl = { path = "packages/ftl" }

async-std = { version = "1.8.0", features = ["attributes"] }
